// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhGQOmZLqsNcjFyCY-JJZwshJcX9DmpDg',
    appId: '1:259290256731:web:3f454ff16355d33debb67e',
    messagingSenderId: '259290256731',
    projectId: 'kuux-project-trace',
    authDomain: 'kuux-project-trace.firebaseapp.com',
    storageBucket: 'kuux-project-trace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UU_gi04qGHu2mYid73b5WtqD2xCb3io',
    appId: '1:259290256731:android:47b1f19e3300becaebb67e',
    messagingSenderId: '259290256731',
    projectId: 'kuux-project-trace',
    storageBucket: 'kuux-project-trace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoD4mH9gYVa1iVfSF2DIDlelp_aSJx_gg',
    appId: '1:259290256731:ios:fd3b549be984ebcdebb67e',
    messagingSenderId: '259290256731',
    projectId: 'kuux-project-trace',
    storageBucket: 'kuux-project-trace.appspot.com',
    iosBundleId: 'com.yan9hwa.kuuxprojecttrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoD4mH9gYVa1iVfSF2DIDlelp_aSJx_gg',
    appId: '1:259290256731:ios:a37635c0c04a4a8debb67e',
    messagingSenderId: '259290256731',
    projectId: 'kuux-project-trace',
    storageBucket: 'kuux-project-trace.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
