// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRFDvEi0Wm-aeCd47lk0eRaYhC-_S78I',
    appId: '1:935922556152:web:8347abe4ed74ef7fdc6f0d',
    messagingSenderId: '935922556152',
    projectId: 'trace-uxdesign',
    authDomain: 'trace-uxdesign.firebaseapp.com',
    storageBucket: 'trace-uxdesign.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfflXRGqJ5lerO_djAaZjdlTYWA-ky9v8',
    appId: '1:935922556152:android:40a207b696965027dc6f0d',
    messagingSenderId: '935922556152',
    projectId: 'trace-uxdesign',
    storageBucket: 'trace-uxdesign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmSdsn4BG7X6vnuD814W1FmbwAui-swNE',
    appId: '1:935922556152:ios:17497a27d73e0c26dc6f0d',
    messagingSenderId: '935922556152',
    projectId: 'trace-uxdesign',
    storageBucket: 'trace-uxdesign.appspot.com',
    iosBundleId: 'com.example.uxDesignProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmSdsn4BG7X6vnuD814W1FmbwAui-swNE',
    appId: '1:935922556152:ios:03a4d73efa36b3f0dc6f0d',
    messagingSenderId: '935922556152',
    projectId: 'trace-uxdesign',
    storageBucket: 'trace-uxdesign.appspot.com',
    iosBundleId: 'com.example.uxDesignProject.RunnerTests',
  );
}
